apiVersion: v1
kind: Service
metadata:
  name: tasks-service # Service 이름 (외부에서 접근 시 minikube service tasks-service 등으로 사용)
spec:
  selector:
    app: tasks # 라벨이 app=tasks 인 Pod로 트래픽 라우팅
  type: LoadBalancer # 클러스터 외부에서 접근 가능하게 하는 Service 타입
  ports:
    - protocol: TCP # L4 프로토콜
      port: 8000 # 클라이언트(브라우저, 외부 시스템)가 접속하는 Service 포트
      targetPort: 8000 # tasks 컨테이너가 실제 리슨하는 포트
