apiVersion: v1
kind: Service # 생성할 리소스 타입, 여기서는 Service
metadata:
  name: story-service # Service 이름 (DNS 이름으로도 사용됨)
spec:
  selector:
    app: story # 라벨이 app=story인 Pod로 트래픽 전달
  ports:
    - protocol: TCP # 사용할 L4 프로토콜 (기본값 TCP)
      port: 80 # Service가 노출하는 포트 (클라이언트가 접근하는 포트)
      targetPort: 3000 # 실제 Pod 컨테이너가 리슨하는 포트
  type: LoadBalancer # Service 타입(ClusterIP, NodePort, LoadBalancer), 여기서는 외부 노출용
